### ISSUE TITLE
problem with large dyson spheres which have a "complex" shape

### ISSUE THREAD

**Issue by Ertyly744** [andyoneal/SphereOpt#2]
I don't know why but I only see the frame, not the shell

![Dyson Sphere Program 10_06_2023 15_40_53](https://github.com/andyoneal/SphereOpt/assets/134539460/dae4c0ed-855f-4c31-b6e2-c360a4a49e15)

i have also other mod, maybee that is the problem, i can test

**Comment by Ertyly744** [comment]
i have also other mod, maybee that is the problem, i can test

**Comment by Ertyly744** [comment]
with only your mod and BepInEx i have the same problem

**Comment by hurricanevu** [comment]
I'm having the same problem. It will only happen if you build the last layer of your sphere

**Comment by andyoneal** [comment]
thanks for reporting this, and sorry it took so long to get back to you.

I reproduced this and I think I've fixed it. will release a new version shortly. @hurricanevu it's exactly this. any shells built on the 10th layer will hit this error.

**Comment by andyoneal** [comment]
fixed. please try v0.8.1 and let me know if this doesn't fix the issue.
