### ISSUE TITLE
Can't change the shell patern

### ISSUE THREAD

**Issue by hurricanevu** [andyoneal/SphereOpt#3]
Hi, thanks for this great mod (improve my fps near the sphere by a ton) I can't however change the sphere pattern, even if I use blueprints it will be converted back to the default pattern. Disabling this mod allows you to do that again. Is this intended or?

**Comment by andyoneal** [comment]
thanks for reporting this, and sorry it took so long to get back to you.

this is sort of intentional, in that I haven't gotten around to it yet. I wanted to make sure it all actually worked before getting into the "cosmetic" stuff. will get to it eventually!

**Comment by andyoneal** [comment]
testing a fix for this. should be done soon.

**Comment by andyoneal** [comment]
fixed in v0.9.0
